### ISSUE TITLE
好像失效了，一直解析

### ISSUE THREAD

**Issue by breezeit** [SeriaWei/NetEaseMusicDownloader#1]
能修复吗？
谢谢！

**Comment by SeriaWei** [comment]
我刚试了还是可以没有问题。

**Comment by SeriaWei** [comment]
![image](https://user-images.githubusercontent.com/6006218/85945031-85778d80-b96d-11ea-9c88-ba25bb87c7d8.png)

**Comment by breezeit** [comment]
排查后发现是我pc上的.net不知道什么时候突然坏掉了。
现在能正常解析了。
